Add the app files
cristian-vijelie/app-libnettletest pull request #1
Opened 2020-12-04 13:45 UTC by cristian-vijelie

2020-12-05 10:56 UTC, craciunoiuc requested changes
Hey Cristi,

I added comments and suggestions about your app. They are mostly about usability and user interaction. Everything else is pretty good.

Please make sure that the kraft build system works properly (or just remove it). Right now it seems that the `yaml` file is the default one from `helloworld`.

Cezar

2020-12-05 10:56 UTC, craciunoiuc commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
Libs do not usually have `lib-` in front of them if referring to the folder.
```suggestion
LIBS := $(UK_LIBS)/nettle:$(UK_LIBS)/newlib
```

2020-12-05 10:56 UTC, craciunoiuc commented on Makefile
> +UK_LIBS ?= $(PWD)/../../libs
Do not forget to add a suggestion in the README for the user to change these lines according to their setup.

2020-12-05 10:56 UTC, craciunoiuc commented on Makefile.uk
> +APPLIBNETTLETEST_SRCS-y += $(APPLIBNETTLETEST_BASE)/main.c
Because this app is specialised in testing `nettle`, maybe you could add the flag `-Wno-missing-prototypes` to the main source for a cleaner build.

```suggestion
APPLIBNETTLETEST_SRCS-y += $(APPLIBNETTLETEST_BASE)/main.c
APPLIBNETTLETEST_MAIN_FLAGS += -Wno-missing-prototypes
```

2020-12-05 10:56 UTC, craciunoiuc commented on include/testsuite.h
> +void test_main_aes(void);
Please add include guards.

```suggestion
#ifndef APP_LIBNETTLETEST_TESTSUITE_H
#define APP_LIBNETTLETEST_TESTSUITE_H
void test_main_aes(void);
```

2020-12-05 10:56 UTC, craciunoiuc commented on include/testsuite.h
> +void test_main_yarrow(void);
```suggestion
void test_main_yarrow(void);
#endif /* APP_LIBNETTLETEST_TESTSUITE_H */
```

2020-12-05 10:56 UTC, craciunoiuc commented on main.c
> +	test_main_aes();
Please print something before and after each test to let users know how far the tests got.

```suggestion
    printf("[1/56] Testing AES encryption...\n");
    rc = test_main_aes();
    printf("AES testing result: ");
    if (!rc) printf("PASSED\n"); else printf("FAILED\n");
```

2020-12-05 10:56 UTC, craciunoiuc commented on main.c
> +
Count the number of tests passed  and failed and print the result at the end.

2020-12-05 10:56 UTC, craciunoiuc commented on kraft.yaml
> +platforms:
If you want to also use kraft, please ensure that all the configurations ar inside the `yaml` file so that no extra `menuconfig` configurations are needed.

2020-12-05 10:56 UTC, craciunoiuc commented on Config.uk
> +	select LIBNEWLIBC
Maybe the test suite should be enabled by default in the test app.

```suggestion
	select LIBNEWLIBC
	select LIBNETTLE_TEST
```

2020-12-05 10:56 UTC, craciunoiuc commented on README.md
> +library.
Add more detailed instructions about what must be additionally configured, like selecting the platform and the test suite etc.

Also, advise the user that the tests will take a while (this can also be done with a `printf`).

2020-12-05 11:19 UTC, craciunoiuc commented on main.c
> +	test_main_aes();
I just saw that your mains return `void`, so you can't check if a test passed or not this way. The idea to print the current test remains anyway.

2020-12-05 11:50 UTC, craciunoiuc commented on main.c
> +
This only works if tests pass as a failed test exits.

2020-12-05 11:55 UTC, craciunoiuc commented on main.c
> +	test_main_yarrow();
These tests fail with the error `Couldn't open gold-bug.txt, errno = 20`. The file is needed when running and it is contained in the library. Rootfs/9pfs will be required.

2020-12-05 11:59 UTC, craciunoiuc commented on Config.uk
> +	select LIBNEWLIBC
Also, add something like to mount a filesystem
```
if PLAT_KVM
	select LIBUK9P
	select LIB9PFS
	select LIBVFSCORE_AUTOMOUNT_ROOTFS
	choice LIBVFSCORE_ROOTFS
		default LIBVFSCORE_ROOTFS_9PFS
	endchoice
```

2020-12-05 12:01 UTC, craciunoiuc commented on Config.uk
> +	select LIBNEWLIBC
Also, add something like to mount a filesystem
```
if PLAT_KVM
	select LIBUK9P
	select LIB9PFS
	select LIBVFSCORE_AUTOMOUNT_ROOTFS
	choice LIBVFSCORE_ROOTFS
		default LIBVFSCORE_ROOTFS_9PFS
	endchoice
```

2020-12-05 13:27 UTC, cristian-vijelie commented on Config.uk
> +	select LIBNEWLIBC
I don't know if the tests should be enabled by default.

2020-12-05 13:33 UTC, craciunoiuc commented on main.c
> +	printf("\t[1]\tMETA AEAD, META ARMOR, META CIPHERS, META HASH, META MAC, AES, ARCTWO, ARCFOUR, BASE16, BASE64, BLOWFISH,\n");
Maybe add an option where all tests are run.

2020-12-05 13:34 UTC, cristian-vijelie commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
That's how the repo's are named, with lib-. I cloned the repo's from the unikraft project.

2020-12-05 13:50 UTC, craciunoiuc commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
I think it's an incosistency from `kraft`. Repo's are named with `lib-` and `app-`, but `kraft` removes that extension when cloning new libraries.

2020-12-05 13:51 UTC, craciunoiuc commented on Config.uk
> +	select LIBNEWLIBC
I was thinking that the role of the app is to run the tests and nothing else. That's why I suggested enabling them.

2020-12-05 13:52 UTC, craciunoiuc commented on main.c
> +	test_main_yarrow();
Only the last test fails.

2020-12-05 14:00 UTC, cristian-vijelie commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
I'm not using kraft to build the app :)
But I'll do the change you requested on the master branch.

2020-12-05 14:00 UTC, cristian-vijelie commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
And I'll leave it like this for the staging one

2020-12-05 14:06 UTC, craciunoiuc commented on Makefile
> +LIBS := $(UK_LIBS)/lib-nettle:$(UK_LIBS)/lib-newlib
No need to change it, just mention in the readme that the path must be adjusted.

2020-12-05 14:06 UTC, cristian-vijelie commented on kraft.yaml
> +platforms:
I'm unfamiliar with the kraft requirements. I must look further into this. I did some changes in kraft.yaml, but I don't know if it's enough

2020-12-05 14:07 UTC, cristian-vijelie commented on Config.uk
> +	select LIBNEWLIBC
Oh. I forgot I'm on the app PR. I'll add it in the app.

2020-12-05 14:09 UTC, cristian-vijelie commented on main.c
> +	test_main_yarrow();
I'm not sure how to fix it. With the file in the same folder as the executable, the test still fails (in linuxu). I must dig further into this.

2020-12-05 14:37 UTC, craciunoiuc commented on main.c
> +	else if (tests_nr == 2 || tests_nr == 0)
Please delete the `else` so in the case where `test_nr == 0` all tests are reached.

2020-12-05 14:37 UTC, craciunoiuc commented on main.c
> +	else if (tests_nr == 2 || tests_nr == 0)
The same in the cases below.

2020-12-05 14:38 UTC, craciunoiuc commented on Config.uk
> +	Select LIBNETTLE_TEST
Typo
```suggestion
	select LIBNETTLE_TEST
```

2021-01-28 16:14 UTC, craciunoiuc requested changes
Hey,

I left some final QoL changes. After this it should be good to go.

Cezar

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +		// test_main_sha1_huge();
Uncomment this. If the user wants to wait 10hrs for this test, let them ;)

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +	fscanf(infile, "%d", &tests_nr);
You forgot to close the file at the end. Also check the return codes for posterity.

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +	sleep(5);
I would make this sleep shorter maybe 1. When running the tests, people would have already chosen a suite. No need to wait more.

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +		sleep(5);
No need for this. The terminal will end anyway and people will be able to read the output.

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +	fscanf(infile, "%d", &tests_nr);
Also, add a switch based on the input to output which suite is select (or no suite for -1).

2021-01-28 16:14 UTC, craciunoiuc commented on guest_fs/test_nr
> +1
Make it `-1` default.

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
> +	infile = fopen("test_nr", "r");
Check return for posterity.

2021-01-28 16:14 UTC, craciunoiuc commented on main.c
>  	return 0;
Don't forget about `fclose`

2021-01-28 16:16 UTC, craciunoiuc commented on main.c
> +		sleep(5);
Referring to sleeps.

2021-01-28 16:40 UTC, cristian-vijelie commented on main.c
> +	fscanf(infile, "%d", &tests_nr);
a switch will double the code size

2021-01-28 16:49 UTC, cristian-vijelie commented on main.c
> +	sleep(5);
one second vs 5 seconds... If they get bored, they can close the kvm

2021-01-28 16:50 UTC, cristian-vijelie commented on main.c
> +		sleep(5);
There may be cases in which they will not configure the qemu like you did, and they will lose the output.

2021-01-28 16:54 UTC, craciunoiuc commented on main.c
> +		sleep(5);
Hmm, I didn't think about this, makes sense.

2021-01-28 16:56 UTC, craciunoiuc commented on main.c
> +	sleep(5);
Yeah, if you think about it, they will only run this once, so 4 seconds is not that much. Anyway it looks good in the current form.

2021-01-28 16:57 UTC, craciunoiuc commented on main.c
> +	fscanf(infile, "%d", &tests_nr);
Yeah, you can leave it like this. I am guessing if they select a test they are able to remember what they chose 10 seconds ago. Leave it like this.

2021-01-28 16:59 UTC, craciunoiuc approved these changes
Hey,

This looks good to me now.

Cezar

2021-01-28 17:00 UTC, merged